import '../core/inventory_enums.dart';
import '../models/item.dart';
import '../models/ownership_record.dart';
import '../models/room.dart';
import '../models/vector3.dart';

class DemoInventory {
  const DemoInventory({
    required this.rooms,
    required this.items,
    required this.history,
  });

  final List<Room> rooms;
  final List<Item> items;
  final List<OwnershipRecord> history;
}

class DemoData {
  static DemoInventory create() {
    final now = DateTime.now();
    final room = Room(
      id: 'room_main',
      name: 'Mein Zimmer',
      width: 4.0,
      depth: 3.2,
      height: 2.5,
      createdAt: now,
      updatedAt: now,
    );

    final desk = Item(
      id: 'item_desk',
      name: 'Schreibtisch',
      alternativeNames: const ['Desk', 'Arbeitsplatz'],
      description: 'Großer Schreibtisch mit Schublade.',
      category: 'Möbel',
      tags: const ['arbeitsplatz', 'container'],
      capabilities: const ['Aufbewahren'],
      properties: const ['Holz', 'stationär'],
      brand: '',
      color: 'Dunkelbraun',
      condition: ItemCondition.good,
      quantity: 1,
      photos: const [],
      createdAt: now,
      updatedAt: now,
      roomId: room.id,
      containerId: null,
      position: const Vector3(x: 2.8, y: 0.7, z: 0.0),
      rotation: const Vector3.zero(),
      size: const Vector3(x: 1.4, y: 0.75, z: 0.7),
      model: PrimitiveModel.cube,
      ownershipStatus: OwnershipStatus.owned,
      isContainer: true,
    );

    final electronicsBox = Item(
      id: 'item_electronics_box',
      name: 'Elektronikbox',
      alternativeNames: const ['Arduino Sachen', 'Elektronikkiste'],
      description: 'Kleine Box für Mikrocontroller und Elektronikteile.',
      category: 'Container',
      tags: const ['elektronik', 'box', 'mikrocontroller'],
      capabilities: const ['Aufbewahren'],
      properties: const ['Kunststoff', 'tragbar'],
      brand: '',
      color: 'Transparent',
      condition: ItemCondition.good,
      quantity: 1,
      photos: const [],
      createdAt: now,
      updatedAt: now,
      roomId: room.id,
      containerId: desk.id,
      position: const Vector3(x: 2.6, y: 0.95, z: 0.85),
      rotation: const Vector3.zero(),
      size: const Vector3(x: 0.45, y: 0.25, z: 0.32),
      model: PrimitiveModel.box,
      ownershipStatus: OwnershipStatus.owned,
      isContainer: true,
    );

    final cableBox = Item(
      id: 'item_cable_box',
      name: 'Kabelbox',
      alternativeNames: const ['Kabelkiste'],
      description: 'Box für Lade- und Datenkabel.',
      category: 'Container',
      tags: const ['kabel', 'usb', 'box'],
      capabilities: const ['Aufbewahren'],
      properties: const ['Kunststoff'],
      brand: '',
      color: 'Grau',
      condition: ItemCondition.good,
      quantity: 1,
      photos: const [],
      createdAt: now,
      updatedAt: now,
      roomId: room.id,
      containerId: desk.id,
      position: const Vector3(x: 3.1, y: 0.95, z: 0.85),
      rotation: const Vector3.zero(),
      size: const Vector3(x: 0.45, y: 0.25, z: 0.32),
      model: PrimitiveModel.box,
      ownershipStatus: OwnershipStatus.owned,
      isContainer: true,
    );

    final ownedItems = [
      desk,
      electronicsBox,
      cableBox,
      Item(
        id: 'item_drill',
        name: 'Akkuschrauber',
        alternativeNames: const ['Bosch Akkuschrauber', 'Bohrschrauber'],
        description: 'Akkubetriebener Schrauber für kleine Reparaturen.',
        category: 'Werkzeug',
        tags: const ['werkzeug', 'akku', 'bohren'],
        capabilities: const ['Schrauben', 'Bohren'],
        properties: const ['Akku', 'tragbar'],
        brand: 'Bosch',
        color: 'Grün',
        condition: ItemCondition.good,
        quantity: 1,
        photos: const [],
        createdAt: now,
        updatedAt: now,
        roomId: room.id,
        containerId: null,
        position: const Vector3(x: 0.7, y: 1.8, z: 1.1),
        rotation: const Vector3.zero(),
        size: const Vector3(x: 0.55, y: 0.22, z: 0.28),
        model: PrimitiveModel.cube,
        ownershipStatus: OwnershipStatus.owned,
        isContainer: false,
      ),
      Item(
        id: 'item_arduino',
        name: 'Arduino Uno',
        alternativeNames: const ['Mikrocontroller', 'Arduino Board'],
        description: 'Entwicklungsboard für Elektronikprojekte.',
        category: 'Elektronik',
        tags: const ['arduino', 'mikrocontroller', 'programmieren'],
        capabilities: const ['Programmieren', 'Mikrocontroller'],
        properties: const ['USB', 'klein'],
        brand: 'Arduino',
        color: 'Blau',
        condition: ItemCondition.good,
        quantity: 1,
        photos: const [],
        createdAt: now,
        updatedAt: now,
        roomId: room.id,
        containerId: electronicsBox.id,
        position: const Vector3(x: 2.55, y: 1.05, z: 1.02),
        rotation: const Vector3.zero(),
        size: const Vector3(x: 0.18, y: 0.03, z: 0.12),
        model: PrimitiveModel.cube,
        ownershipStatus: OwnershipStatus.owned,
        isContainer: false,
      ),
      Item(
        id: 'item_usb_c',
        name: 'USB-C Kabel',
        alternativeNames: const ['USB C Kabel', 'Ladekabel', 'Datenkabel'],
        description: 'Kabel zum Laden und zur Datenübertragung.',
        category: 'Elektronik',
        tags: const ['usb', 'kabel', 'laden'],
        capabilities: const ['Laden', 'Datenübertragung'],
        properties: const ['USB-C', 'flexibel'],
        brand: '',
        color: 'Schwarz',
        condition: ItemCondition.good,
        quantity: 3,
        photos: const [],
        createdAt: now,
        updatedAt: now,
        roomId: room.id,
        containerId: cableBox.id,
        position: const Vector3(x: 3.0, y: 1.05, z: 1.02),
        rotation: const Vector3.zero(),
        size: const Vector3(x: 0.28, y: 0.05, z: 0.14),
        model: PrimitiveModel.cylinder,
        ownershipStatus: OwnershipStatus.owned,
        isContainer: false,
      ),
      Item(
        id: 'item_scissors',
        name: 'Schere',
        alternativeNames: const ['Papierschere'],
        description: 'Schere für Papier, Folie und Verpackungen.',
        category: 'Werkzeug',
        tags: const ['schneiden', 'werkzeug'],
        capabilities: const ['Schneiden'],
        properties: const ['Metall', 'tragbar'],
        brand: '',
        color: 'Rot',
        condition: ItemCondition.good,
        quantity: 1,
        photos: const [],
        createdAt: now,
        updatedAt: now,
        roomId: room.id,
        containerId: null,
        position: const Vector3(x: 1.5, y: 1.2, z: 0.8),
        rotation: const Vector3.zero(),
        size: const Vector3(x: 0.3, y: 0.04, z: 0.12),
        model: PrimitiveModel.cube,
        ownershipStatus: OwnershipStatus.owned,
        isContainer: false,
      ),
    ];

    final soldDate = DateTime(2026, 8, 25);
    final soldItem = Item(
      id: 'item_old_keyboard',
      name: 'Alte Tastatur',
      alternativeNames: const ['Keyboard'],
      description: 'Mechanische Tastatur, nicht mehr im Besitz.',
      category: 'Elektronik',
      tags: const ['verkauft', 'tastatur'],
      capabilities: const ['Tippen'],
      properties: const ['USB'],
      brand: '',
      color: 'Schwarz',
      condition: ItemCondition.used,
      quantity: 1,
      photos: const [],
      createdAt: now,
      updatedAt: now,
      roomId: room.id,
      containerId: null,
      position: null,
      rotation: const Vector3.zero(),
      size: const Vector3.one(),
      model: PrimitiveModel.cube,
      ownershipStatus: OwnershipStatus.sold,
      isContainer: false,
    );

    return DemoInventory(
      rooms: [room],
      items: [...ownedItems, soldItem],
      history: [
        OwnershipRecord(
          id: 'history_keyboard_sold',
          itemId: soldItem.id,
          status: OwnershipStatus.sold,
          salePrice: 20,
          person: 'Example',
          date: soldDate,
          note: 'Über Kleinanzeigen verkauft',
          createdAt: now,
        ),
      ],
    );
  }
}
